route:
  receiver: admin

receivers:
- name: admin
  email_configs:
  - to: 'mbotelaj84@gmail.com'
    from: 'jimbotela@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'jimbotela@gmail.com'
    auth_identity: 'jimbotela@gmail.com'
    auth_password: 'hpblraxgordnfbxi'